---
title: "Relatório - Aula 1"
author: "Douglas Cardoso"
date: "8/25/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercício 1
```{r }
tibble::tibble(
  
  precos = c(5800, 5300, 5900, 5400, 6300, 6900,
             6400, 6200, 5900, 5400, 5200, 5800,
             5400, 5200, 5800, 5300, 6200, 6800,
             6300, 6400)) |> 
  dplyr::summarise(
    MEDIA = mean(precos),
    MEDIANA = median(precos),
    DESVIO_PADRAO = sd(precos),
    COEF_VARIAÇAO = DESVIO_PADRAO / MEDIA * 100) |>
  
  knitr::kable(caption = 'Estatísticas básicas sobre os preços',
               digits = 2,
               col.names = c('Média', 'Mediana', 'Desvio padrão', 'Coeficiente de variação'))
```
# Exercício 2

```{r}
# Tabela
tibble::tibble(
  nomes = c("José", "Bonifácio", "Almerindo", "Fred", "Abílio", "João"),
  '2014' = c(160, 140, 90, 150, 95, 175),
  '2015' = c(180, 145, 95, 145, 110, 145),
  '2016' = c(210, 165, 110, 140, 125, 290),
  '2017' = c(250, 130, 420, 155, 150, 250))  |>
  
  tidyr::pivot_longer('2014':'2017', names_to = 'ano', values_to = 'produtividade') |>
  dplyr::mutate(ano = as.integer(ano)) -> digitadores

digitadores |>
  knitr::kable(caption ='Produtividade de cada digitador por ano' ,
               col.names = c('Nome', 'Ano', 'Produtividade'))
```
### Visualização gráfica
```{r}
digitadores |>
  ggplot2::ggplot(ggplot2::aes(x = ano, y = produtividade, group = nomes, colour = nomes)) +
  ggplot2::geom_line(size = 1.2) +
  ggplot2::theme_minimal() +
  ggplot2::labs(x = 'Ano', y = 'Média', title = 'Produtividade média dos digitadores por ano')
```

## Produtividade total média
```{r}
digitadores |>
  dplyr::summarise(media_total = mean(produtividade)) |>
  dplyr::mutate(print = glue::glue('A produtividade média total é de {round(media_total, 2)}')) |> 
  dplyr::pull(print)
```
## Produtividade média por ano
```{r}
digitadores |>
  dplyr::group_by(ano) |>
  dplyr::summarise(media = mean(produtividade), .groups = 'drop') |>
  
  knitr::kable(caption = 'Produtividade média por ano',
               col.names = c('Ano', 'Média'))
```

## Produtividade por digitadores
```{r}
digitadores |>
  dplyr::group_by(nomes) |>
  dplyr::summarise(media = mean(produtividade), .groups = 'drop') |>
  
  knitr::kable(caption = 'Produtividade média por digitador',
               col.names = c('Nome', 'Média'))
```

## Desvio padrão e coeficiente de variação do total produzido 
```{r}
digitadores |>
  dplyr::summarise(média_total = mean(produtividade),
                   desvio_padrão = sd(produtividade),
                   coef_variação = desvio_padrão / média_total * 100) |>

  knitr::kable(caption = 'Estatísticas básicas sobre o total produzido',
                 digits = 2,
               col.names = c('Média total', 'Desvio padrão', 'Coeficiente de variação'))
```

## Qual digitador possui menor produtividade mediana?
```{r}
digitadores |>
  dplyr::group_by(nomes) |>
  dplyr::summarise(mediana = median(produtividade)) |>
  dplyr::filter(mediana == min(mediana)) |>
  dplyr::mutate(print = glue::glue('A menor produtividade mediana é do {nomes}, com {mediana}')) |>
  dplyr::pull(print)
```







